services:
  redis:
    container_name: redis
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/devops-system/redis:7.4
    network_mode: host
    command:
      - --requirepass Mm852bw7zaMyyjhZAcxr
      - --appendonly yes
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/database/redis:/var/lib/redis
