---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: database
  labels:
    app.kubernetes.io/name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: database
  labels:
    app.kubernetes.io/name: mongo
spec:
  replicas: 1
  serviceName: mongo
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-001
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mongo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mongo
        image: registry.cn-hangzhou.aliyuncs.com/devops-system/mongo:8.0
        imagePullPolicy: IfNotPresent
        args:
        - --bind_ip_all
        - --maxConns=200
        ports:
        - containerPort: 27017
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "PCamTwR4sQkM8T5VhBN2"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: mongo
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
