apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka
  namespace: middleware
type: Opaque
stringData:
  server-jaas.properties: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="password"
        user_admin="password"
        user_kafka="changeme";
    };
  client-jaas.properties: |
    security.protocol: SASL_PLAINTEXT
    sasl.mechanism: PLAIN
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="changeme";
