services:
  postgres:
    container_name: postgres
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/devops-system/postgres:17.4
    command:
      - --max_connections=200
      - --timezone=Asia/Shanghai
      - --log_timezone=Asia/Shanghai
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mm852bw7zaMyyjhZAcxr
    network_mode: host
    volumes:
      - /data/database/postgres:/var/lib/postgresql/data
