apiVersion: v1
kind: Service
metadata:
  name: vmstorage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmstorage
spec:
  clusterIP: None
  ports:
    - port: 8482
      targetPort: http
      protocol: TCP
      name: http
    - port: 8401
      targetPort: vmselect
      protocol: TCP
      name: vmselect
    - port: 8400
      targetPort: vminsert
      protocol: TCP
      name: vminsert
  selector:
    app.kubernetes.io/name: vmstorage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmstorage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmstorage
spec:
  replicas: 3
  serviceName: vmstorage
  selector:
    matchLabels:
      app.kubernetes.io/name: vmstorage
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vmstorage
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - "vmstorage"
            topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: true
      containers:
        - name: vmstorage
          image: registry.cn-hangzhou.aliyuncs.com/devops-system/vmstorage:v1.125.1-cluster
          imagePullPolicy: IfNotPresent
          args:
            - --retentionPeriod=3
            - --storageDataPath=/storage
            - --dedup.minScrapeInterval=30s
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8482
            - name: vminsert
              containerPort: 8400
            - name: vmselect
              containerPort: 8401
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 16
              memory: 32Gi
            requests:
              cpu: 16
              memory: 32Gi
          volumeMounts:
            - name: vmstorage
              mountPath: /storage
      serviceAccountName: victoriametrics
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: vmstorage
      spec:
        storageClassName: vmstorage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "100Gi"
