apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmstorage-2
  namespace: monitoring
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-003
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vmstorage
  local:
    path: /data/volume/vmstorage-2
