- job_name: 'kube-etcd'
  metrics_path: /metrics
  http_sd_configs:
    - url: https://devops.kubeop.com/api/v1/monitor/targets?cluster=%{CLUSTER}&module=kube-etcd
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
