apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerd
  namespace: infra
  labels:
    app.kubernetes.io/name: dockerd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockerd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockerd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: docker
                operator: In
                values:
                - "true"
      containers:
        - name: dockerd
          image: registry.cn-hangzhou.aliyuncs.com/kubeop/docker:28-dind
          imagePullPolicy: Always
          args:
            - --registry-mirror=https://docker.gh-proxy.com
            - --registry-mirror=https://jkf6gc4u.mirror.aliyuncs.com
            - --registry-mirror=https://docker.zhai.cm
            - --registry-mirror=https://docker.1ms.run
            - --registry-mirror=https://dockerproxy.net
            - --registry-mirror=https://docker.1panel.live
            - --registry-mirror=https://hub.rat.dev
            - --registry-mirror=https://dockerproxy.net
            - --registry-mirror=https://image.cloudlayer.icu
            - --registry-mirror=https://docker-registry.nmqu.com
            - --registry-mirror=https://hub.amingg.com
            - --registry-mirror=https://docker.amingg.com
            - --registry-mirror=https://docker.hlmirror.com
            - --registry-mirror=https://docker.kejilion.pro
            - --registry-mirror=https://docker.apiba.cn
            - --registry-mirror=https://proxy.vvvv.ee
            - --registry-mirror=https://docker.fnnas.com
            - --insecure-registry=registry.kubeop.com
            - --bip=192.168.100.1/24
            - --data-root=/data/docker
          securityContext:
            privileged: true
          env:
          - name: TZ
            value: Asia/Shanghai
          volumeMounts:
            - mountPath: /var/run
              name: docker-sock
            - mountPath: /data/docker
              name: docker-data
      volumes:
        - name: docker-data
          hostPath:
            path: /data/docker
        - name: docker-sock
          hostPath:
            path: /var/run
