apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: infra
  labels:
    app.kubernetes.io/name: "jenkins"
    app.kubernetes.io/component: "jenkins-controller"
type: Opaque
data:
  jenkins-admin-password: "YWRtaW4="
  jenkins-admin-user: "YWRtaW4="
