---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
          multiline.pattern: '^\d{4}-\d{2}-\d{2}'
          multiline.negate: true
          multiline.match: after

    # 处理json日志
    processors:
      - add_fields:
          target: ""
          fields:
            cluster: "ops-pro"
      - drop_fields:
          fields: ["agent","ecs","container","kubernetes.node.labels"]
    #   - decode_json_fields:
    #       fields: ["message"]
    #       target: ""
    #       overwrite_keys: true

    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST}"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      parameters:
        _msg_field: "message"
        _time_field: "@timestamp"
        _stream_fields: "cluster,kubernetes.namespace,kubernetes.container.name"
        ignore_fields: "log.offset,event.original,agent,ecs,input,container,host"
      compression_level: 1
