apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
     providers:
       - type: kubernetes
         node: ${NODE_NAME}
         hints.enabled: true
         hints.default_config:
           type: filestream
           id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
           paths:
           - /var/log/containers/*-${data.kubernetes.container.id}.log
           parsers:
           - container: ~
           prospector:
            scanner:
              fingerprint.enabled: true
              symlinks: true
           file_identity.fingerprint: ~

    processors:
      - add_fields:
          target: ""
          fields:
            cluster: "${CLUSTER_NAME}"
      - drop_fields:
          fields: ["agent","ecs","container","kubernetes.node.labels"]
      - add_cloud_metadata:
      - add_host_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_URL}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      parameters:
        _msg_field: "message"
        _time_field: "@timestamp"
        _stream_fields: "cluster,kubernetes.namespace,kubernetes.container.name"
        ignore_fields: "log.offset,event.original,agent,ecs,input,container,host"
      compression_level: 1
      worker: 8
      bulk_max_size: 1000
      allow_older_versions: true