apiVersion: v1
kind: ConfigMap
metadata:
  name: nameserver-conf
  labels:
    app.kubernetes.io/name: nameserver
    app.kubernetes.io/instance: rocketmq
data:
  namesrv.p: |
    listenPort=9876
    defaultThreadPoolNums=4
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-nameserver
  labels:
    app.kubernetes.io/name: nameserver
    app.kubernetes.io/instance: rocketmq
spec:
  clusterIP: None
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: nameserver-service
  selector:
    app.kubernetes.io/name: nameserver
    app.kubernetes.io/instance: rocketmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-nameserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nameserver
      app.kubernetes.io/instance: rocketmq
      component: nameserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nameserver
        app.kubernetes.io/instance: rocketmq
        component: nameserver
    spec:
      containers:
        - name: nameserver
          image: registry.cn-hangzhou.aliyuncs.com/devops-system/rocketmq:5.3.3
          imagePullPolicy: "IfNotPresent"
          command: [ "/bin/sh" ]
          args: [ "-c", "./mqnamesrv -c /home/rocketmq/config/namesrv.p" ]
          env:
            - name: JAVA_HEAP_SIZE
              value: 1792M
          ports:
            - name: nameserver
              containerPort: 9876
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: nameserver
            periodSeconds: 5
            initialDelaySeconds: 20
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: nameserver
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: nameserver
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi
          volumeMounts:
            - mountPath: /home/rocketmq/config
              name: nameserver-config
            - mountPath: /home/rocketmq/logs
              name: nameserver-log
      volumes:
        - name: nameserver-config
          configMap:
            name: nameserver-conf
        - name: nameserver-log
          emptyDir: { }
