apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: dcgm-exporter
subjects:
- kind: ServiceAccount
  name: dcgm-exporter
  namespace: kube-system
roleRef:
  kind: Role 
  name: dcgm-exporter-read-cm
  apiGroup: rbac.authorization.k8s.io
