global:
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels:
    cluster: %{CLUSTER}

scrape_config_files:
- https://vmconfig.kubeop.com/scrape_config/configs/kube-etcd.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kube-apiserver.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kube-controller-manager.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kube-scheduler.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kubelet.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kube-proxy.yml
- https://vmconfig.kubeop.com/scrape_config/configs/kube-state-metrics.yml
