apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
    prometheus.io/path: "/metrics"
    prometheus.io/exporter: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: dcgm-exporter
spec:
  type: ClusterIP
  ports:
  - name: "metrics"
    port: 9400
    targetPort: 9400
    protocol: TCP
  selector:
    app.kubernetes.io/name: dcgm-exporter
