apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: exporter
  labels:
    app.kubernetes.io/name: redis-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: redis-exporter
