apiVersion: v1
kind: PersistentVolume
metadata:
  name: vtstorage-1
  namespace: tracing
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-002
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vtstorage
  local:
    path: /data/volume/vtstorage-1