---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vtstorage
  name: vtstorage
  namespace: tracing
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 10491
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vtstorage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: vtstorage
  name: vtstorage
  namespace: tracing
spec:
  serviceName: vtstorage
  selector:
    matchLabels:
      app.kubernetes.io/name: vtstorage
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vtstorage
    spec:
      containers:
        - name: vtstorage
          image: registry.cn-hangzhou.aliyuncs.com/devops-system/victoria-traces:v0.2.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          args:
            - --envflag.enable
            - --http.shutdownDelay=15s
            - --httpListenAddr=:10491
            - --loggerFormat=json
            - --retentionPeriod=3
            - --storageDataPath=/storage
          ports:
            - name: http
              containerPort: 10491
          resources:
            limits:
              cpu: 8
              memory: 16Gi
            requests:
              cpu: 8
              memory: 16Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: vtstorage-volume
              mountPath: /storage
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
  minReadySeconds: 5
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: vtstorage-volume
      spec:
        storageClassName: vtstorage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi