groups:
- name: blackbox
  rules:
  - alert: 站点拨测失败
    expr: |-
      probe_success == 0
    for: 1m
    labels:
      severity: P1
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}拨测失败, 请检查网络或服务是否正常"

  - alert: 站点一小时可用性过低
    expr: |-
      sum_over_time(probe_success[1h])/count_over_time(probe_success[1h]) * 100 < 90
    for: 1m
    labels:
      severity: P2
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}在一小时内可用性低于90%, 触发时值为: {{ $value }}%"

  - alert: 站点响应时间过长
    expr: avg_over_time(probe_duration_seconds[1m]) > 5
    for: 2m
    labels:
      severity: P3
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}拨测响应时间超过5秒, 触发时值为: {{ $value | humanizeDuration }}"

  - alert: 站点HTTP状态码异常
    expr: (probe_success == 0 and probe_http_status_code >= 400)
    for: 1m
    labels:
      severity: P2
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}返回的状态码不在200-399之间, 触发时值为: {{ $value }}"

  - alert: 站点证书即将过期
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: 1m
    labels:
      severity: P4
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}的证书即将在{{$value | humanizeDuration}}天内过期"

  - alert: 站点证书即将过期
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
    for: 1m
    labels:
      severity: P3
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}的证书即将在{{$value | humanizeDuration}}天内过期"

  - alert: 站点证书即将过期
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 1
    for: 1m
    labels:
      severity: P2
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}的证书即将在{{$value | humanizeDuration}}天内过期"

  - alert: 站点证书已经过期
    expr: probe_ssl_earliest_cert_expiry - time() <= 0
    for: 1m
    labels:
      severity: P1
    annotations:
      description: "实例{{ $labels.job }}/{{ $labels.instance }}的证书已过期{{$value | humanizeDuration}}天"
