---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: redis-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: redis-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: registry.cn-hangzhou.aliyuncs.com/devops-system/redis-exporter:v1.76.0
        imagePullPolicy: IfNotPresent
        args:
        - --web.listen-address=:9121
        - --web.telemetry-path=/metrics
        - --redis.user=exporter
        - --redis.password=exporter
        - --include-system-metrics
        - --log-format=json
        ports:
        - name: metrics
          containerPort: 9121
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          failureThreshold: 1
          tcpSocket:
            port: 9121
          initialDelaySeconds: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 9
        readinessProbe:
          failureThreshold: 1
          tcpSocket:
            port: 9121
          initialDelaySeconds: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 9
