apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: exporter
  labels:
    app.kubernetes.io/name: mysqld-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9104
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: mysqld-exporter
