groups:
- name: node-exporter
  rules:
  - alert: NodeDown
    expr: |
      up{job=~"node-exporter"} == 0
    for: 1m
    labels:
      severity: P1
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}超过1分钟不可用"

  - alert: NodeLoad
    expr: |
      avg_over_time(instance:node_load5_per_cpu:ratio{job="node-exporter"}[5m]) > 1.8
    for: 10m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的系统负载超过90%, 触发时值为: {{ $value | humanizePercentage }}"

  - alert: NodeCpuUsage
    expr: |
      avg_over_time(instance:node_cpu_utilisation:rate5m{job="node-exporter"}[5m]) > 0.85
    for: 5m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的CPU使用率超过85%, 触发时值为: {{ $value | humanizePercentage }}"

  - alert: NodeMemoryUsage
    expr: |
      avg_over_time(instance:node_memory_utilisation:ratio{job="node-exporter"}[5m]) > 0.85
    for: 5m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的内存使用率超过85%, 触发时值为: {{ $value | humanizePercentage }}"

  - alert: NodeOomKillDetected
    expr: (increase(node_vmstat_oom_kill[1m]) > 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 0m
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}检测到有OOM Killer"

  - alert: NodeHighNumberConntrackEntriesUsed
    expr: |
      (node_nf_conntrack_entries{job="node-exporter"} / node_nf_conntrack_entries_limit{job="node-exporter"}) > 0.75
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的conntrack已使用超过75%, 触发时值为: {{ $value | humanizePercentage }}"

  - alert: NodeCpuIowait
    expr: (avg by (cluster, job, instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 10) * on(cluster, job, instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 5m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的CPU iowait大于10%, iowait过高意味着磁盘或网络可能受限, 触发时值为: {{ printf \"%.2f\" $value }}%"

  - alert: NodeNetworkReceiveErrs
    expr: |
      rate(node_network_receive_errs_total{job="node-exporter"}[2m]) / rate(node_network_receive_packets_total{job="node-exporter"}[2m]) > 0.01
    for: 1h
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的网络接口{{ $labels.device }}入方向在最近2分钟有超过{{ $value | humanize }}%的错误"

  - alert: NodeNetworkTransmitErrs
    expr: |
      rate(node_network_transmit_errs_total{job="node-exporter"}[2m]) / rate(node_network_transmit_packets_total{job="node-exporter"}[2m]) > 0.01
    for: 1h
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的网络接口{{ $labels.device }}出方向在最近2分钟有超过{{ $value | humanize }}%的错误"

  - alert: NodeTextFileCollectorScrapeError
    expr: |
      node_textfile_scrape_error{job="node-exporter"} == 1
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的监控采集器无法抓取数据"

  - alert: NodeFileDescriptorLimit
    expr: |
      (
        node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 70
      )
    for: 15m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的文件描述符已使用超过70%, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFileDescriptorLimit
    expr: |
      (
        node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 90
      )
    for: 15m
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的文件描述符已使用超过90%, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeNetworkInterfaceFlapping
    expr: changes(node_network_up{job="node-exporter",device!~"veth.+"}[2m]) > 2
    for: 2m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}的网络接口{{ $labels.device }}在最近2分钟变更过{{ $value }}次状态"

  - alert: NodeFilesystemAlmostOutOfSpace
    expr: |
      (
        node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 15
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 30m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余空间不足15%, 请及时清理空间, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFilesystemAlmostOutOfSpace
    expr: |
      (
        node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 10
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 30m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余空间不足10%, 请及时清理空间, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFilesystemAlmostOutOfSpace
    expr: |
      (
        node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 30m
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余空间不足5%, 请及时清理空间, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFilesystemAlmostOutOfSpace
    expr: |
      (
        node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 30m
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余空间不足5%, 请及时清理空间, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFilesystemAlmostOutOfFiles
    expr: |
      (
        node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余inode不足5%, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeFilesystemAlmostOutOfFiles
    expr: |
      (
        node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: P2
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的设备{{ $labels.device }}挂载点{{ $labels.mountpoint }}剩余inode不足3%, 触发时值为: {{ $value | humanize }}%"

  - alert: NodeClockSkewDetected
    expr: |
      (
        node_timex_offset_seconds > 0.05
      and
        deriv(node_timex_offset_seconds[5m]) >= 0
      )
      or
      (
        node_timex_offset_seconds < -0.05
      and
        deriv(node_timex_offset_seconds[5m]) <= 0
      )
    for: 10m
    labels:
      severity: P4
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的时钟超过300秒没有同步, 请确保该主机正确配置了NTP"

  - alert: NodeClockNotSynchronising
    expr: |
      min_over_time(node_timex_sync_status[5m]) == 0
      and
      node_timex_maxerror_seconds >= 16
    for: 10m
    labels:
      severity: P4
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的时钟未进行同步, 请确保该主机正确配置了NTP"

  - alert: NodeRAIDDegraded
    expr: |
      node_md_disks_required - ignoring (state) (node_md_disks{state="active"}) > 0
    for: 15m
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的磁盘阵列{{ $labels.device }}处于degraded状态, 请检查磁盘阵列状态"

  - alert: NodeRAIDDiskFailure
    expr: |
      node_md_disks{state="failed"} > 0
    labels:
      severity: P3
    annotations:
      description: "主机实例{{ $labels.job }}/{{ $labels.instance }}上的磁盘阵列{{ $labels.device }}中至少有一个设备发生故障"

- name: windows-exporter
  rules:
  - alert: WindowsDown
    expr: |
      up{job="windows-exporter"} == 0
    for: 1m
    labels:
      severity: P2
    annotations:
      description: "Windows实例{{ $labels.job }}/{{ $labels.instance }}超过1分钟不可用"

  - alert: WindowsCpuUsage
    expr: |
       100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100) > 85
    for: 5m
    labels:
      severity: P3
    annotations:
      description: "Windows实例{{ $labels.job }}/{{ $labels.instance }}的CPU使用率超过85%, 触发时值为: {{ $value | humanize }}%"

  - alert: WindowsMemoryUsage
    expr: |
      100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100) > 85
    for: 5m
    labels:
      severity: P3
    annotations:
      description: "Windows实例{{ $labels.job }}/{{ $labels.instance }}的内存使用率超过85%, 触发时值为: {{ $value | humanize }}%"

  - alert: WindowsFilesystemAlmostOutOfSpace
    expr: |
      100.0 - 100 * ((windows_logical_disk_free_bytes / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)) > 90
    for: 30m
    labels:
      severity: P3
    annotations:
      description: "Windows实例{{ $labels.job }}/{{ $labels.instance }}的分区{{ $labels.volume }}使用率超过90%, 触发时值为: {{ $value | humanize }}%"
