---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/name: vlstorage
  name: vlstorage
  namespace: logging
spec:
  type: ClusterIP
  clusterIP: None
  ports: 
    - port: 9491
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    app.kubernetes.io/name: vlstorage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: 
    app.kubernetes.io/name: vlstorage
  name: vlstorage
  namespace: logging
spec:
  serviceName: vlstorage
  selector:
    matchLabels: 
      app.kubernetes.io/name: vlstorage
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: vlstorage
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - vlstorage
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: vlstorage
          image: registry.cn-hangzhou.aliyuncs.com/devops-system/victoria-logs:v1.21.0-victorialogs
          imagePullPolicy: IfNotPresent
          securityContext: 
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          args: 
            - --retentionPeriod=7d
            - --storageDataPath=/storage
            - --envflag.enable
            - --httpListenAddr=:9491
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 9491
          resources:
            limits:
              cpu: 8
              memory: 16Gi
            requests:
              cpu: 8
              memory: 16Gi
          readinessProbe: 
            failureThreshold: 10
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: vlstorage-volume
              mountPath: /storage
      securityContext: 
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
  minReadySeconds: 5
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: vlstorage-volume
      spec:
        storageClassName: vlstorage
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
---
