---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9308"
    prometheus.io/path: "/metrics"
    prometheus.io/exporter: "kafka-exporter"
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: kafka-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: registry.cn-hangzhou.aliyuncs.com/devops-system/kafka-exporter:v1.9.0
        imagePullPolicy: IfNotPresent
        args:
          - --kafka.server=kafka-0.kafka.middleware.svc.cluster.local:9092
          - --kafka.server=kafka-1.kafka.middleware.svc.cluster.local:9092
          - --kafka.server=kafka-2.kafka.middleware.svc.cluster.local:9092
          - --sasl.enabled
          - --sasl.username=kafka
          - --sasl.password=changeme
          - --sasl.mechanism=plain
          - --web.listen-address=:9308
          - --web.telemetry-path=/metrics
          - --topic.filter=.*
          - --group.filter=.*
          - --log.level=info
          - --log.format=json
        ports:
        - name: metrics
          containerPort: 9308
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "200m"
            memory: 512Mi
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 9308
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 9
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 9308
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 9