apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: exporter
  labels:
    app.kubernetes.io/name: postgres-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: postgres-exporter
